### ISSUE TITLE
dev

### ISSUE THREAD

**Issue by magenta808** [mlaude545/DeathTrap-Dungeon#1]
the dev is a poopy butt face

**Comment by mlaude545** [comment]
This is a well known issue, working on a fix to that now

**Comment by magenta808** [comment]
there is no fix

**Comment by mlaude545** [comment]
Damn, this got weirdly deep

**Comment by mlaude545** [comment]
Closing this as, whilst I may be a poopy butt face, I keep seeing the issue notification at the top of the screen and thinking something else has been opened.
